Solution/GotadiFrontend/Presentation/Controllers/HotelDetailController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.IO;
using ExpediaModels;

namespace Presentation.Controllers
{
    public class HotelDetailController : Controller
    {
        // GET: HotelDetail
        public ActionResult Index(string country, string city, string hotel)
        {
            // Load rate type detail
            var lst = new ExpediaBusiness.RoomBL().GetRoomRateDetail();

            // Load room images
            var roomImages = new ExpediaBusiness.ImageBL().GetRoomImages("");

            ViewBag.RoomImages = roomImages;


            lst = Helpers.ReformatObjectString.FormatHotelDetail(lst, (HotelSearchCriteriaDO)Session["SEARCH_CRITERIAS"]);
            return View("~/Views/HotelDetail/HotelDetail.cshtml", lst);
        }

        [HttpPost]
        public ActionResult InputCustomer(string hotelcode, string room_type, string room_code)
        {
            return View();
        }
        
    }


}

Solution/GotadiFrontend/Presentation/Views/HotelDetail/RoomDetail.cshtml
@using ExpediaModels

@model RoomDetailDO
@{
    List<HotelImage> lst = ViewBag.RoomImages;
    string CurrentRoomURL = (from a in lst
                             where a.HotelImageId.Equals(Model.RoomCode)
                             select a.Url).FirstOrDefault();
}
 

@*@using (Html.BeginForm("InputCustomer", "HotelDetail", FormMethod.Post))
{
    Html.Hidden("CurrentAllotment", Model.CurrentAllotment.ToString());*@
    
<li>
    <div class="row">
        <div class="col-sm-4">
            <img src="@CurrentRoomURL" class="img-responsive" alt="" />
        </div>
        <div class="col-sm-8" style="height:100%;">
            <div class="row" style="height:100%;">
                <div class="col-sm-8 room-info">
                    <h3><strong><a href="#@Model.RoomCode" data-toggle="collapse">@Model.RoomDescription</a></strong></h3>
                    <p>Chúng tôi còn <strong class="text-success">@Model.CurrentAllotment</strong> phòng</p>
                    <ul class="list-inline list-items">
                        @{
                            if (Model.ValueAdds.Where(t => t.id.Equals("2192")).Count() > 0)
                            {
                                <li class="icon_free_wifi"> @Model.ValueAdds.Where(t => t.id.Equals("2192")).Select(a => a.description).FirstOrDefault()</li>
                            }
                            if (Model.ValueAdds.Where(t => t.id.Equals("2104")).Count() > 0)
                            {
                                <li class="icon_free_breakfast"> @Model.ValueAdds.Where(t => t.id.Equals("2104")).Select(a=>a.description).FirstOrDefault()</li>
                            }
                            if (Model.ValueAdds.Where(t => t.id.Equals("2196")).Count() > 0)
                            {
                                <li class="icon_free_pickup"> @Model.ValueAdds.Where(t => t.id.Equals("2196")).Select(a => a.description).FirstOrDefault()</li>
                            }
                        }
                    </ul>
                     
                </div>
                <div class="col-sm-4 price-info">
                    <div class="price">VND <span class="text-success">@Model.TotalAmount</span></div>
                    <div class="text-primary">Giảm giá 30%</div>
                    <a class="btn btn-block btn_book" href="@Model.RoomBookLink">Đặt ngay</a>
                    
                     @*@Html.ActionLink("Đặt ngay", "Index", "InputCustomer",
                     new {  hotelcode = ViewBag.HotelDetail.HotelID,
                         room_type = Model.RoomTypeId,
                         room_code = Model.RoomCode,
                         checkin = "2015-12-23",
                         checkout = "2015-12-25"
                     },
                                    new { @class = "btn btn-block btn_book" })*@ 
                </div>
            </div>

            
        </div>
        <!-- Expanded Detail: BEGIN-->
        <div id="@Model.RoomCode" class="col-sm-12 collapse">
            <div class="text-success"><p><strong>Thông tin phòng</strong></p></div>
            <p>@Html.Raw(HttpUtility.HtmlDecode(Model.DescriptionLong))</p>

            <div class="text-success"><p><strong>Chính sách hủy</strong></p></div>
            <p>@Html.Raw(HttpUtility.HtmlDecode(Model.RateInfos[0].cancellationPolicy))</p>
        </div>
        <!-- Expanded Detail: BEGIN-->
    </div>
</li>
@*}*@